version: '3'
services:
  web:
    build: .
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5000
    volumes:
      - .:/app
    restart: unless-stopped